### ISSUE TITLE
Revisar con Juano

### ISSUE THREAD

**Issue by lucascisneros00** [lucascisneros00/IE_Cisneros_Freyre#3]
- [x] Revisar con Juano comments de review de VRI
- [x] Preguntar a Juano si podemos pagar en efectivo a participantes

**Comment by alecfreyre** [comment]
- [x] Revisar con Juano instrucciones del experimento

- [x] Revisar con Juano tamaño de muestra

- [x] Revisar con Juano posibilidades de conferencia
